-- This file is for use with Rapanui Framework
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["drink"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1.5, -32.5  ,  -6.5, 77.5  ,  -17.5, 73.5  ,  -28.5, -22.5  ,  -25.5, -30.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   38, -21  ,  28, 67  ,  24, 76  ,  -6.5, 77.5  ,  -1.5, -32.5  ,  8.5, -33.5  ,  36.5, -29.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -29.5, -89.5  ,  2, -65  ,  -6, -62  ,  -32, -84  ,  -30.5, -89.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2, -65  ,  8.5, -33.5  ,  0, -36  ,  -6, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8.5, -33.5  ,  -1.5, -32.5  ,  0, -36  }
                    }
                    
                    
                    
		}
		
		, 
		["hamburger"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43.5, -15.5  ,  -36, -23  ,  -22, -29  ,  13, -32  ,  -42.5, 0.5  ,  -47.5, -5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   26, 34  ,  -34, 31  ,  45.5, 12.5  ,  48.5, 15.5  ,  43.5, 29.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   39, -5  ,  14, -32  ,  30, -30  ,  40, -25  ,  48.5, -12.5  ,  47, -7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42.5, 14.5  ,  -37.5, 23.5  ,  -45.5, 17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   45.5, 12.5  ,  -34, 31  ,  13, -32  ,  14, -32  ,  39, -5  ,  46.5, 4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42.5, 0.5  ,  13, -32  ,  -37.5, 23.5  ,  -42.5, 14.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.3, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -32  ,  -34, 31  ,  -37.5, 23.5  }
                    }
                    
                    
                    
		}
		
		, 
		["hotdog"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   40.5, -25.5  ,  0, 28  ,  -30, 29  ,  -42, 26  ,  -8, -20  ,  29, -34  ,  37, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -57.5, -2.5  ,  -50, -13  ,  -8, -20  ,  -42, 26  ,  -56.5, 13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   58.5, -7.5  ,  52.5, 1.5  ,  30, 18  ,  0, 28  ,  40.5, -25.5  ,  59.5, -15.5  }
                    }
                    
                    
                    
		}
		
		, 
		["icecream"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   59.5, -32  ,  36, -7.5  ,  30, -8.5  ,  47, -33.5  ,  56, -40.5  ,  57, -40.5  ,  60.5, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, -23.5  ,  3.5, -18  ,  -11, -16.5  ,  -8, -22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   39.5, 16  ,  29.5, 27  ,  13, 37.5  ,  -29, 37.5  ,  -37, -13.5  ,  36, -7.5  ,  42.5, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, -30.5  ,  3.5, -18  ,  0, -23.5  ,  1.5, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   7.5, -13  ,  -21, -12.5  ,  -11, -16.5  ,  3.5, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, -3.5  ,  -37, -13.5  ,  -29, 37.5  ,  -51, 23.5  ,  -58, 12.5  ,  -59.5, 2  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -8.5  ,  -21, -12.5  ,  7.5, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 3, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   36, -7.5  ,  -21, -12.5  ,  30, -8.5  }
                    }
                    
                    
                    
		}
		
		, 
		["icecream2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -0.5, -40  ,  -4.5, 22  ,  -13, 22.5  ,  -22, 16.5  ,  -22, -31.5  ,  -10.5, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 45.5  ,  6, 21.5  ,  14.5, 22  ,  15, 44.5  ,  11.5, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 21.5  ,  2, 19.5  ,  7.5, -45  ,  8.5, -45  ,  20, -29.5  ,  20, 18.5  ,  14.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -13, 22.5  ,  -4.5, 22  ,  -6, 46.5  ,  -12.5, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   7.5, -45  ,  2, 19.5  ,  -4.5, 22  ,  -0.5, -40  }
                    }
                    
                    
                    
		}
		
		, 
		["icecream3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, -40.5  ,  1, -49.5  ,  13, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4, 55.5  ,  -11.5, 11  ,  0, -49.5  ,  1, -49.5  ,  12.5, 1  ,  2.5, 51  ,  0.5, 55  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   12.5, 1  ,  1, -49.5  ,  11, -40.5  ,  18.5, -30  ,  22.5, -16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   -23.5, -28  ,  -18.5, -37  ,  0, -49.5  ,  -19.5, -10  ,  -23.5, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0.2, restitution = 0, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, -49.5  ,  -11.5, 11  ,  -19.5, -10  }
                    }
                    
                    
                    
		}
		
		, 
		["floor"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -242, 14  ,  -370.68017578125, 66.9324321746826  ,  -371.981979370117, -111.378372192383  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   372.684692382812, 66.6306304931641  ,  260.5, 2.5  ,  371.481994628906, -152.716217041016  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   10, -9  ,  21, -7  ,  37, 0  ,  68, 27  ,  -26.5, 17.5  ,  -14, -2  ,  -3, -8  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -128, 7  ,  -109, 13  ,  -72, 30  ,  -157, 24  ,  -144, 10  ,  -138, 7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   372.684692382812, 66.6306304931641  ,  247, 16  ,  260.5, 2.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   372.684692382812, 66.6306304931641  ,  229, 26  ,  247, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   68, 27  ,  -35.5, 26.5  ,  -26.5, 17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -225, 22  ,  -370.68017578125, 66.9324321746826  ,  -242, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -196, 30  ,  -370.68017578125, 66.9324321746826  ,  -225, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -72, 30  ,  -59, 33  ,  -168, 30  ,  -157, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -196, 30  ,  -59, 33  ,  372.684692382812, 66.6306304931641  ,  -370.68017578125, 66.9324321746826  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   175, 19  ,  207, 28  ,  112, 30  ,  149, 17  ,  156.5, 16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   68, 27  ,  82, 32  ,  -48, 32  ,  -35.5, 26.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   372.684692382812, 66.6306304931641  ,  207, 28  ,  229, 26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   372.684692382812, 66.6306304931641  ,  93, 33  ,  112, 30  ,  207, 28  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   82, 32  ,  372.684692382812, 66.6306304931641  ,  -59, 33  ,  -48, 32  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end

return M

