-- This file is for use with Rapanui Framework
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["c_shape1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   16.9000015258789, 4  ,  14.9000015258789, -12  ,  28.4000015258789, -5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   -12.6000003814697, -9.5  ,  1.40000152587891, -0.5  ,  -16.1000003814697, -1  ,  -31.1000000238419, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   1.40000152587891, -0.5  ,  -8.10000038146973, 12  ,  -25.5999999046326, 15.5  ,  -25.0999999046326, 12  ,  -16.1000003814697, -1  }
                    }
                     ,
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   20.4000015258789, 20.5  ,  11.4000015258789, 15.5  ,  16.9000015258789, 4  ,  24.9000015258789, 21  }
                    }
                     ,
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   6.40000152587891, 14.5  ,  1.40000152587891, -0.5  ,  4.90000152587891, -13  ,  14.9000015258789, -12  ,  16.9000015258789, 4  ,  11.4000015258789, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   1.40000152587891, -0.5  ,  6.40000152587891, 14.5  ,  -0.100000381469727, 29  ,  -2.60000038146973, 30.5  ,  -8.10000038146973, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "Star", density = 2, friction = 0.1, restitution = 0.5, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   14.9000015258789, -12  ,  4.90000152587891, -13  ,  14.9000015258789, -31  ,  16.9000015258789, -32  }
                    }
                    
                    
                    
		}
		
		, 
		["c_shape2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   -22.6666669845581, -48.5  ,  -8.66666603088379, -44.5  ,  -2.66666603088379, -40.5  ,  -15.6666660308838, -37.5  ,  -23.6666669845581, -46.5  ,  -24.1666665077209, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   11.8333320617676, -46  ,  5.33333206176758, -49.5  ,  14.8333320617676, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   -23.6666669845581, -18.5  ,  -24.1666665077209, -20  ,  -15.1666660308838, -29  ,  -6.16666603088379, -29  ,  -9.16666603088379, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   3.83333206176758, -50  ,  -2.66666603088379, -40.5  ,  -4.16666603088379, -48  ,  -1.16666603088379, -60  ,  0.833332061767578, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   14.8333320617676, -9  ,  13.3333320617676, -8.5  ,  3.83333206176758, -18  ,  5.33333206176758, -29.5  ,  11.8333320617676, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   24.8333320617676, -47  ,  15.8333320617676, -38  ,  15.3333320617676, -45.5  ,  23.3333320617676, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   15.8333320617676, -38  ,  11.8333320617676, -46  ,  15.3333320617676, -45.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   15.8333320617676, -38  ,  -2.66666603088379, -40.5  ,  3.83333206176758, -50  ,  5.33333206176758, -49.5  ,  11.8333320617676, -46  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   -2.66666603088379, -40.5  ,  15.8333320617676, -38  ,  28.3333320617676, -34.5  ,  5.33333206176758, -29.5  ,  -15.1666660308838, -29  ,  -26.6666665077209, -32.5  ,  -27.6666665077209, -34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   5.33333206176758, -29.5  ,  28.3333320617676, -34.5  ,  28.8333320617676, -33  ,  16.3333320617676, -29.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   0.833332061767578, -5.66666412353516  ,  5.33333206176758, -29.5  ,  3.83333206176758, -18  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   5.33333206176758, -29.5  ,  -6.16666603088379, -29  ,  -15.1666660308838, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   5.33333206176758, -29.5  ,  -2.5, -20.3333358764648  ,  -6.16666603088379, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   5.33333206176758, -29.5  ,  1.66666793823242, -4.83333587646484  ,  -2.5, -20.3333358764648  }
                    }
                     ,
                    {
                    pe_fixture_id = "Head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = -1 },
                    shape = {   5.33333206176758, -29.5  ,  1.66666793823242, -4.83333587646484  ,  0.833332061767578, -5.66666412353516  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "SensorA", density = 2, friction = 0, restitution = 0, sensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -20, 59  ,  -19.6666669845581, 30.6666679382324  ,  -5, 30.3333320617676  ,  17, 30.6666679382324  ,  17.6666679382324, 60  }
                    }
                     ,
                    {
                    pe_fixture_id = "SensorA", density = 2, friction = 0, restitution = 0, sensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, -25.3333358764648  ,  3.66666793823242, 29  ,  -5, 30.3333320617676  ,  -5, -27.6666641235352  }
                    }
                     ,
                    {
                    pe_fixture_id = "SensorA", density = 2, friction = 0, restitution = 0, sensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   17, 30.6666679382324  ,  -5, 30.3333320617676  ,  3.66666793823242, 29  }
                    }
                    
                    
                    
		}
		
		, 
		["c_shape3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191.5, -23  ,  191.5, 31  ,  163, -3.5  ,  184, -21.5  ,  190, -24.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   101, -1.5  ,  57, -2.5  ,  77, -12.5  ,  86, -12.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   145, 3.5  ,  106, -1.5  ,  121, -7.5  ,  130, -7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -165, -16.5  ,  -139, 7.5  ,  -192.5, 30  ,  -192.5, -5  ,  -185.5, -13  ,  -175, -18.5  ,  -169, -18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14, -16.5  ,  22, -14.5  ,  42, -3.5  ,  1, -7.5  ,  9, -15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -121, 2.5  ,  -74, 4.5  ,  -133, 9.5  ,  -129, 5.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -33, -16.5  ,  -5, -5.5  ,  -63, -1.5  ,  -48, -13.5  ,  -40, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191.5, 31  ,  151, 4.5  ,  163, -3.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5, -5.5  ,  42, -3.5  ,  -74, 4.5  ,  -63, -1.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -133, 9.5  ,  -192.5, 30  ,  -139, 7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42, -3.5  ,  49, -1.5  ,  -192.5, 30  ,  -133, 9.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42, -3.5  ,  -5, -5.5  ,  1, -7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191.5, 31  ,  190, 31.5  ,  -192.5, 30  ,  49, -1.5  ,  106, -1.5  ,  145, 3.5  ,  151, 4.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   101, -1.5  ,  49, -1.5  ,  57, -2.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "basic_fixture", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -192.5, 30  ,  190, 31.5  ,  -192, 31.5  }
                    }
                    
                    
                    
		}
		
		, 
		["c_shape4"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "head", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 10.667,
                    center = { x=2.667, y=-20.000}
                    }
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "leftArm", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22.1666669845581, -6.33333206176758  ,  -5.66666603088379, -6.16666793823242  ,  -5.66666603088379, -0.666667938232422  ,  -22.1666669845581, -0.333332061767578  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "rightArm", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26.6666679382324, -0.833332061767578  ,  11, -0.833332061767578  ,  11.5, -7.16666793823242  ,  27.1666679382324, -7.33333206176758  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "leftLeg", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10.1666660308838, 27  ,  -15.3333339691162, 24.1666665077209  ,  -8.5, 11.8333339691162  ,  -2.83333396911621, 15.1666660308838  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "rightLeg", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   15.3333320617676, 27.3333334922791  ,  8, 15.1666660308838  ,  12.1666679382324, 12.6666660308838  ,  21, 23.8333330154419  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "torso", density = 2, friction = 0, restitution = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   10.3333320617676, -8  ,  10.1666679382324, 15.8333339691162  ,  -5, 14.3333339691162  ,  -5.83333396911621, -8  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end
	
	return physics;
end

return M

